### ISSUE TITLE
Unable to connect zigbee2mqtt to SLZB-06 via ethernet

### ISSUE THREAD

**Issue by beol** [smlight-dev/slzb-06-firmware#12]
I've recently purchased SLZB-6 from AliExpress. I've been unable to connect it to my z2m setup via ethernet with:
```
Zigbee2MQTT:debug 2023-01-19 19:53:40: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2023-01-19 19:53:40: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-01-19.19-53-39' filename: log.txt                     
Zigbee2MQTT:debug 2023-01-19 19:53:40: Removing old log directory '/opt/zigbee2mqtt/data/log/2023-01-19.18-15-18'
Zigbee2MQTT:info  2023-01-19 19:53:40: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6)
Zigbee2MQTT:info  2023-01-19 19:53:40: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:debug 2023-01-19 19:53:40: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"auto","baudRate":115200,"path":"tcp://192.168.86.183:6638"}}'
Zigbee2MQTT:error 2023-01-19 19:54:01: Error while starting zigbee-herdsman    
Zigbee2MQTT:error 2023-01-19 19:54:01: Failed to start zigbee                  
Zigbee2MQTT:error 2023-01-19 19:54:01: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions           
Zigbee2MQTT:error 2023-01-19 19:54:01: Exiting...                              
Zigbee2MQTT:error 2023-01-19 19:54:01: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)                                 
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)                     
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)            
    at start (/opt/zigbee2mqtt/index.js:107:5)                                 
```

```
Device information                                                                 
Model:  SLZB-06                                                                    
ESP32 Firmware ver: 0.9.8 (Jan 2 2023)                                             
ESP32 version:  ESP32-D0WDQ5                                                       
ESP32 temperature:  43.00 °C                                                       
ESP32 frequency:    2 cores @ 240 MHz                                              
ESP32 flash size:   16 Mb, external                                                
ESP32 Free heap:    231 / 303 KiB                                                  
CC2652P version:    CC2652PP1FRGZR                                                 
CC2652P frequency:  48 MHz                                                         
CC2652P flash size: 352 Kb                   
```

I've updated the firmware and also the re-flash the coordinator firmware. I can connect it via USB to my raspberry pi, and make it work with zigbee2mqtt but have not been able via ethernet.

**Comment by sergge1** [comment]
hi, please submit your request through the [ticketing system](https://smlight.tech/support/) so support will contact you and will figure out your problem.

**Comment by beol** [comment]
I've reached out here because I can't tell whether my submission to the ticketing system was received or not, there has been no acknowledgement of ticket being created.

**Comment by senz** [comment]
Hello. same problem here.
Also had submitted a request with your system, but no answer.
This repo is about a firmware for a specific device (its even in the name of the repo), so lets discuss this problem here, for benefit of the other people facing exact same issue.
What info do you need for debugging @sergge1 ?

**Comment by sergge1** [comment]
Dear visitors, I am maintaining ESP firmware here. For inquiries about the device itself (everything that does not relate to the ESP firmware) - please contact them via ticketing or email. Thank you!
